"""empty message

Revision ID: c008216c5368
Revises: 
Create Date: 2021-06-11 06:21:48.669982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c008216c5368"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Show",
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["Artist.id"],
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["Venue.id"],
        ),
        sa.PrimaryKeyConstraint("venue_id", "artist_id"),
    )
    op.add_column("Artist", sa.Column("website", sa.String(length=120), nullable=True))
    op.add_column("Artist", sa.Column("seeking_venue", sa.Boolean(), nullable=True))
    op.add_column(
        "Artist", sa.Column("seeking_description", sa.String(length=120), nullable=True)
    )
    op.add_column(
        "Artist", sa.Column("past_shows", sa.String(length=120), nullable=True)
    )
    op.add_column("Artist", sa.Column("past_shows_count", sa.Integer(), nullable=True))
    op.add_column(
        "Artist", sa.Column("upcoming_shows", sa.String(length=120), nullable=True)
    )
    op.add_column(
        "Artist", sa.Column("upcoming_shows_count", sa.Integer(), nullable=True)
    )
    op.add_column("Venue", sa.Column("genres", sa.String(length=120), nullable=True))
    op.add_column("Venue", sa.Column("website", sa.String(length=120), nullable=True))
    op.add_column("Venue", sa.Column("seeking_talent", sa.Boolean(), nullable=True))
    op.add_column(
        "Venue", sa.Column("seeking_description", sa.String(length=120), nullable=True)
    )
    op.add_column(
        "Venue", sa.Column("past_shows", sa.String(length=120), nullable=True)
    )
    op.add_column("Venue", sa.Column("past_shows_count", sa.Integer(), nullable=True))
    op.add_column(
        "Venue", sa.Column("upcoming_shows", sa.String(length=120), nullable=True)
    )
    op.add_column(
        "Venue", sa.Column("upcoming_shows_count", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Venue", "upcoming_shows_count")
    op.drop_column("Venue", "upcoming_shows")
    op.drop_column("Venue", "past_shows_count")
    op.drop_column("Venue", "past_shows")
    op.drop_column("Venue", "seeking_description")
    op.drop_column("Venue", "seeking_talent")
    op.drop_column("Venue", "website")
    op.drop_column("Venue", "genres")
    op.drop_column("Artist", "upcoming_shows_count")
    op.drop_column("Artist", "upcoming_shows")
    op.drop_column("Artist", "past_shows_count")
    op.drop_column("Artist", "past_shows")
    op.drop_column("Artist", "seeking_description")
    op.drop_column("Artist", "seeking_venue")
    op.drop_column("Artist", "website")
    op.drop_table("Show")
    # ### end Alembic commands ###
